name: GraphQL Regression

on:
  push:
    branches: [ main ]

jobs:
  Regression:

    name: Run test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git project
      uses: actions/checkout@v4

    - name: Install packages
      run: npm ci
    
    - name: Run lint and test
      run: npm run lint&&export GO_RES_USER_TOKEN=${{ secrets.API_TOKEN }}&&export ENV=dev&&npm test
    
    - name: Create Report
      uses: phoenix-actions/test-reporting@v8
      id: test-report
      if: success() || failure()
      with:
        name: Generate Result
        path: report/index.json
        reporter: mochawesome-json
